#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server_auth_login:
    path:  /oauth/v2/auth_login
    controller: App\Controller\Security:Security:login 

oauth_server_auth_login_check:
    path:  /oauth/v2/auth_login_check
    controller: App\Controller\Security:Security:loginCheck 